# Generated by Django 4.2.6 on 2023-10-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('gyrox', models.FloatField(blank=True, null=True)),
                ('gyroy', models.FloatField(blank=True, null=True)),
                ('gyroz', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': True,
            },
        ),
    ]
