# Generated by Django 4.2.6 on 2023-11-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('Acc_x', models.FloatField(blank=True, null=True)),
                ('Acc_y', models.FloatField(blank=True, null=True)),
                ('Acc_z', models.FloatField(blank=True, null=True)),
                ('Gyro_x', models.FloatField(blank=True, null=True)),
                ('Gyro_y', models.FloatField(blank=True, null=True)),
                ('Gyro_z', models.FloatField(blank=True, null=True)),
                ('DateTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': True,
            },
        ),
    ]
