# Generated by Django 4.2.6 on 2023-12-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_dogstatus_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Breed', models.CharField(blank=True, max_length=100, null=True)),
                ('Weight', models.FloatField(blank=True, null=True)),
                ('Height', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Dog',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='mealamount',
            old_name='DatTime',
            new_name='DateTime',
        ),
    ]
